backend:
  name: github
  repo: "mdcfe/netlify-cms-demo"
  branch: main
  open_authoring: true

publish_mode: editorial_workflow
media_folder: "images/uploads"

collections:
  - name: "wiki"
    label: "Wiki"
    folder: "content/wiki"
    create: true
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}