backend:
  name: github
  repo: "mdcfe/netlify-cms-demo"
  branch: main
  open_authoring: true

site_url: https://angry-agnesi-6d26d3.netlify.app/
publish_mode: editorial_workflow
media_folder: "images/uploads"

collections:
  - name: "wiki"
    label: "Wiki"
    folder: "content/wiki"
    create: true
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "wiki"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
    preview_path: "#/{{slug}}"